# Generated by Django 4.1.3 on 2022-11-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_ultimo_nome_usuario_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='confirmar_senha',
            field=models.CharField(default=2, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default=16, max_length=16),
            preserve_default=False,
        ),
    ]
