# Generated by Django 4.1.3 on 2022-11-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_usuario_confirmar_senha_usuario_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='confirmar_senha',
        ),
    ]
