# Generated by Django 4.1.3 on 2022-11-30 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_usuario_confirmar_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('numero_de_telefone', models.CharField(max_length=30)),
                ('endereco', models.EmailField(max_length=254)),
                ('selecione_o_funcionario', models.CharField(blank=True, choices=[('gregorio', 'gregorio'), ('jose', 'jose'), ('gabriela', 'gabriela'), ('laura', 'laura')], max_length=100, null=True)),
                ('selecione_o_sevico', models.CharField(blank=True, choices=[('1 people', '1 people'), ('2 people', '2 people'), ('3 people', '3 people'), ('4 people', '4 people')], max_length=100, null=True)),
                ('data_de_agendamento', models.DateField()),
                ('horario', models.CharField(blank=True, choices=[('08:00 às 09:00', '08:00 às 09:00'), ('09:00 às 10:00', '09:00 às 10:00'), ('10:00 às 11:00', '10:00 às 11:00'), ('11:00 às 12:00', '11:00 às 12:00'), ('13:00 às 14:00', '13:00 às 14:00'), ('14:00 às 15:00', '14:00 às 15:00'), ('15:00 às 16:00', '15:00 às 16:00'), ('16:00 às 17:00', '16:00 às 17:00'), ('17:00 às 18:00', '17:00 às 18:00'), ('18:00 às 19:00', '18:00 às 19:00')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=120)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicos_preenchido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.agendamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.servicos')),
            ],
        ),
        migrations.AddField(
            model_name='servicos',
            name='preenchido',
            field=models.ManyToManyField(through='myapp.Servicos_preenchido', to='myapp.agendamento'),
        ),
    ]
