# Generated by Django 4.1.3 on 2022-12-01 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_agendamento_servicos_servicos_preenchido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='data_de_agendamento',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='numero_de_telefone',
        ),
    ]
