# Generated by Django 4.1.3 on 2022-12-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_data_de_agendamento_agendamento_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='nome_completo',
            new_name='nome',
        ),
    ]
