# Generated by Django 4.1.3 on 2022-12-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_nome_completo_agendamento_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='horario',
            new_name='hora',
        ),
    ]
