# Generated by Django 4.1.3 on 2022-12-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_horario_agendamento_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='selecione_o_funcionario',
            new_name='funcionario',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='hora',
            new_name='horario',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='selecione_o_sevico',
            new_name='sevico',
        ),
    ]
