# Generated by Django 4.1.3 on 2022-12-01 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_selecione_o_funcionario_agendamento_funcionario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='sevico',
            new_name='servico',
        ),
    ]
